import os 

env = SConscript('../godot_cpp/SConstruct')
env.Append(CPPPATH=['src'])
dest_dir ='../../src/bin/Gong/'

num_jobs = ARGUMENTS.get('jobs',12)
platform = ARGUMENTS.get('platform','windows')

src = Glob('src/*.cpp')
libpath ='{}libGong{}{}'.format(dest_dir,env['suffix'],env['SHLIBSUFFIX'])
sharedlib = env.SharedLibrary(libpath,src)
Default(sharedlib)    